
# this is the name of the main maude module 
LANGUAGE_NAME = JS

# this are all interesting modules (used to latexify)
# LANGUAGE_MODULES = IMPPP-SYNTAX IMPPP-SEMANTICS IMPPP

#this is the basename of the main file
MAIN_FILE = js

# this is a space-separated list of basename maude files to run
TESTS = js-test.m


# LANGUAGE_NAME = JSON-TO-PREFIX
# MAIN_FILE = json2prefix
# TESTS = js2prefix-test.m


TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk


