#!/usr/bin/env bash

file="$1" && shift

semantics_dir="../../../.."

pushd programs/$file

krun --search --smt_prelude "$K_RELEASE/include/z3/basic.smt2" \
     --directory "$semantics_dir" \
     $@ main_pass.c

krun --search --smt_prelude "$K_RELEASE/include/z3/basic.smt2" \
     --directory "$semantics_dir" \
     $@ main_fail.c

popd
