// Copyright (c) 2016 K Team. All Rights Reserved.
module TEST [Location(#token("3",Int@INT-SYNTAX),#token("1",Int@INT-SYNTAX),#token("5",Int@INT-SYNTAX),#token("9",Int@INT-SYNTAX)) Source(#token("src/test/resources/convertor-tests/simpleSyntax.k",KString@KSTRING))]
  syntax Foo@TEST [Location(#token("4",Int@INT-SYNTAX),#token("3",Int@INT-SYNTAX),#token("4",Int@INT-SYNTAX),#token("12",Int@INT-SYNTAX)) Source(#token("src/test/resources/convertor-tests/simpleSyntax.k",KString@KSTRING))]
endmodule
