COMPILE_OPTIONS=-pdf

# this is the name of the main maude module 
LANGUAGE_NAME = AGENTS	

#this is the basename of the main file
MAIN_FILE = agents


TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk

