#!/usr/bin/env bash
if [[ `uname` == *MINGW* || `uname` == *MSYS* || `uname` == *CYGWIN* ]]; then
  "$(dirname "$0")/k.bat" "$@"
else
  source "$(dirname "$0")/setenv"
  ulimit -s `ulimit -H -s`
  export K_OPTS="-XX:+TieredCompilation -XX:+AggressiveOpts $K_OPTS"
  if "$(dirname "$0")/checkJava"; then
    if [[ `uname` == *MINGW* || `uname` == *CYGWIN* ]]; then
      NG=ng.exe
    else
      NG=ng
    fi
    $NG ng-version > /dev/null 2>&1
    if [ $? -eq 0 ]; then
      $NG org.kframework.main.Main "$@"
    else
      java -Djava.awt.headless=true -Djava.library.path="$THE_LIBRARY_PATH" $K_OPTS -ea -cp "$(dirname "$0")/java/*" org.kframework.main.Main "$@"
    fi
  else
    exit 1
  fi
fi
